
package:
  name: otf-general
  version: "0.1.0"

source:
  path: ..

build:
  noarch: 0
  script: bash build.sh
  
requirements:
  host:
    - python >=3.9
    - pip
    - pymbar ==4.0.3
    - alchemlyb ==2.3.1
    - scipy ==1.8.1
  run:
    - python >=3.9
    - pymbar ==4.0.3
    - alchemlyb ==2.3.1
    - scipy ==1.8.1

about:
  home: https://github.com/MGKurnikovaGroup/otf_general_public
  license: MIT
  license_file: LICENSE
  summary: "On-The-Fly Optimization for alchemical binding free energy simulations using AMBER"
  description: |
    Implements the OTF optimization workflow for ABFE simulations
    using thermodynamic integration in AMBER20. See 10.26434/chemrxiv-2023-rtpsz.

extra:
  recipe-maintainers:
    - Isk-101

