package:
  name: otf-general
  version: "0.1.0"

source:
  git_url: https://github.com/MGKurnikovaGroup/otf_general_public.git
  git_rev: Package

build:
  noarch: python # This specifies it's a pure Python package
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  # You can also use a build.sh file for this, but this is a common shortcut.
  
requirements:
  host:
    - python >=3.0
    - pip
    - pymbar ==4.0.3
    - alchemlyb ==2.3.1
    - scipy ==1.8.1
  run:
    - python >=3.0
    - pymbar ==4.0.3
    - alchemlyb ==2.3.1
    - scipy ==1.8.1

about:
  home: https://github.com/MGKurnikovaGroup/otf_general_public
  license: MIT
  license_file: LICENSE
  summary: "On-The-Fly Optimization for alchemical binding free energy simulations using AMBER"
  description: |
    Implements the OTF optimization workflow for ABFE simulations
    using thermodynamic integration in AMBER20. See 10.26434/chemrxiv-2023-rtpsz.

extra:
  recipe-maintainers:
    - Isk-101

